#!/bin/sh

RETRYN=20

call() {
  status=
  data_message=

  TMP=`mktemp`
  if ! curl -s -o "$TMP" --basic -u "$collins_user:$collins_password" -H \
    'Accept: text/x-shellscript' "$@"
  then
    echo "FATAL ERROR: Couldn't connect to collins"
    exit 1
  fi
  . "$TMP"
  rm "$TMP"
}

log() {
  message=$1
  severity=$2
  echo "$severity: $message"
  call -X PUT -d "message=$message" -d type="$severity" \
    "$asset_url/log"
}

for f in `cat /proc/cmdline | tr ' ' '\n' | grep ^collins_`
do
    export $f
done

if [ -z "$collins_url" -o \
     -z "$collins_user" -o \
     -z "$collins_password" -o \
     -z "$collins_tag" ]
then
  echo "collins parameters not found in /proc/cmdline:"
  cat /proc/cmdline
  exit 1
fi

asset_url="$collins_url/asset/$collins_tag"

call $asset_url
if [ -n "$ASSET_STATUS" ]
then
  if [ "$ASSET_STATUS" == "Allocated" ]
  then
    log "Asset already allocated" "CRITICAL" 
    exit 1
  fi
  log "Asset already registered" "WARNING"
else
  call -X PUT -d "generate_ipmi=false" $asset_url
  if [ "$status" == "error" ]
  then
    log "Couldn't create asset: $data_message" "CRITICAL"
    exit 1
  fi
fi

echo "Registering $collins_tag:"
echo -n " - Waiting for lldp"
while [ -z "`lldpctl -f keyvalue`" ]
do
  i=$((i+1))
  echo -n '.'
  sleep 1
  if [ "$i" -gt "$RETRYN" ]
  then
    echo "[ERR]"
    log "lldpctl failed" "CRITICAL"
    LLDP_FAILED=1
    break
  fi
done
echo "[OK]"


# We need to POST a fake lldp file because of
# https://github.com/tumblr/collins/issues/116
if [ -z "$LLDP_FAILED" ]
then
  LLDP_TMP=`mktemp`
  lldpctl -f xml > "$LLDP_TMP"
else
  LLDP_TMP="/etc/fake-lldp.xml"
fi

LSHW_TMP=`mktemp`
lshw -xml > "$LSHW_TMP"
call --data-urlencode "lldp@$LLDP_TMP" \
     --data-urlencode "lshw@$LSHW_TMP" \
     --data-urlencode "CHASSIS_TAG=`cat /sys/class/dmi/id/board_serial`" \
     --data-urlencode "POWER_OUTLET_A=Unknown" \
     --data-urlencode "POWER_PORT_A=Unknown" \
     $asset_url
if [ "$status" == "error" ]
then
  log "updating asset failed: $data_message"
fi
