#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/var/run/lldpd

cp -v etc/*             ${DESTDIR}/etc
cp -v register          ${DESTDIR}/bin
cp -v /etc/resolv.conf  ${DESTDIR}/etc

for b in curl lshw lldpd lldpctl
do
	copy_exec `PATH=/bin:/sbin:/usr/bin:/usr/sbin which $b` /bin
done

# copied from hooks/mountall
for file in libnss_files.so.2 libnss_dns.so.2
do
  f=`dpkg -L libc6 | grep $file`
  if [ -f $f ]; then
    cp -uv $f ${DESTDIR}/lib/$file
  else
    echo "$file not found"
    echo "warning: mountall would not be able to connect to upstart"
    exit 1
  fi
done
