#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /usr/share/initramfs-tools/hook-functions

mkdir -p ${DESTDIR}/var/run/lldpd

cp -v etc/*        ${DESTDIR}/etc
cp -v register     ${DESTDIR}/bin

for b in curl lshw lldpd lldpctl
do
	copy_exec `PATH=/bin:/sbin:/usr/bin:/usr/sbin which $b` /bin
done

# copied from hooks/mountall
libnss_files=`dpkg -L libc6 | grep libnss_files.so.2`
if [ -f $libnss_files ]; then
  cp -uv $libnss_files ${DESTDIR}/lib/libnss_files.so.2
else
  echo "libnss_files.so.2 not found"
  echo "warning: mountall would not be able to connect to upstart"
  exit 1
fi

